spring:
  datasource:
    url: jdbc:h2:./data/database;AUTO_SERVER=TRUE

logging:
  level:
    root: warn
    xyz.bromine0x23.shiningco: info

casbin:
  model: classpath:casbin/model.conf
  policy: classpath:casbin/policy.csv
  store-type: file

# 账号配置
bot:
  account: 10000
  password-md5: ffffffffffffffffffffffffffffffff
  # password: password


shiningco:
  plugins:
    pixiv:
      refresh-token: <refresh-token>
      proxy:
        type: direct